name: Hello World
on : push 

jobs: 
    greeting:
        runs-on: ubuntu-latest
        steps:
            - name: "Greeting!"
              run: echo hello world
    test-ptho-3-12:
        name: Check  Python 3.12 on Ubuntu
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: "3.12"
            - name: Install package
              run: python -m pip install -e . 
            
            - name: Test package 
              run: python -m pytest 




                