name: Hello World
on: push

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: "Greeting!"
        run: echo hello world
        
  test-python-version:
    name: Check Python ${{matrix.python-version}} on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install package
        run: python -m pip install -e .[test]
      - name: Test package
        run: python -m pytest




                